# Generated by Django 5.2.1 on 2025-09-11 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='analises/')),
                ('img_resultado', models.ImageField(blank=True, null=True, upload_to='resultados/')),
                ('n_plaquetas', models.IntegerField(blank=True, null=True)),
                ('n_celulas_brancas', models.IntegerField(blank=True, null=True)),
                ('n_celulas_vermelhas', models.IntegerField(blank=True, null=True)),
                ('n_linfocitos', models.IntegerField(blank=True, null=True)),
                ('n_monocitos', models.IntegerField(blank=True, null=True)),
                ('n_basofilos', models.IntegerField(blank=True, null=True)),
                ('n_neutrofilos_banda', models.IntegerField(blank=True, null=True)),
                ('n_neutrofilos_segmentados', models.IntegerField(blank=True, null=True)),
                ('n_mielocitos', models.IntegerField(blank=True, null=True)),
                ('n_metamielocitos', models.IntegerField(blank=True, null=True)),
                ('n_promielocitos', models.IntegerField(blank=True, null=True)),
                ('n_eosinofilos', models.IntegerField(blank=True, null=True)),
                ('acuracia', models.FloatField(blank=True, null=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('erro_msg', models.TextField(blank=True, null=True)),
                ('tempo_processamento', models.FloatField(blank=True, null=True)),
                ('detalhes_processamento', models.JSONField(blank=True, null=True)),
                ('confianca_deteccao', models.FloatField(blank=True, null=True)),
                ('metadados_modelo', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Análise',
                'verbose_name_plural': 'Análises',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ImagemAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='analises/')),
                ('imagem_resultado', models.ImageField(blank=True, null=True, upload_to='resultados/')),
                ('n_plaquetas', models.IntegerField(blank=True, null=True)),
                ('n_celulas_brancas', models.IntegerField(blank=True, null=True)),
                ('n_celulas_vermelhas', models.IntegerField(blank=True, null=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_analise', to='Analises.analise')),
            ],
            options={
                'verbose_name': 'Imagem da Análise',
                'verbose_name_plural': 'Imagens das Análises',
            },
        ),
    ]
