# Generated by Django 5.1.4 on 2025-01-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='analises/')),
                ('img_resultado', models.ImageField(blank=True, null=True, upload_to='resultados/')),
                ('n_plaquetas', models.IntegerField(blank=True, null=True)),
                ('acuracia', models.FloatField(blank=True, null=True)),
                ('tempo_analise', models.FloatField(blank=True, null=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Análise',
                'verbose_name_plural': 'Análises',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
