# Generated by Django 5.1.4 on 2025-02-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise',
            name='historico_modificacoes',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='ultima_modificacao',
        ),
    ]
