# Generated by Django 5.2.1 on 2025-09-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='duracao_video',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='esta_gravando',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analise',
            name='tipo_analise',
            field=models.CharField(choices=[('imagem', 'Imagem Única'), ('tempo_real', 'Tempo Real'), ('video', 'Vídeo')], default='imagem', max_length=20),
        ),
        migrations.AddField(
            model_name='analise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='analises/videos/'),
        ),
        migrations.AddField(
            model_name='analise',
            name='video_resultado',
            field=models.FileField(blank=True, null=True, upload_to='resultados/videos/'),
        ),
    ]
