# Generated by Django 5.1.5 on 2025-01-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise',
            name='tempo_analise',
        ),
        migrations.AddField(
            model_name='analise',
            name='erro_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
    ]
