# Generated by Django 5.1.5 on 2025-03-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0002_remove_analise_historico_modificacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='n_basofilos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='n_eosinofilos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='n_linfocitos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='n_metamielocitos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='n_mielocitos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='n_monocitos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='n_neutrofilos_banda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='n_neutrofilos_segmentados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='n_promielocitos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
