# Generated by Django 5.1.5 on 2025-01-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0002_remove_analise_tempo_analise_analise_erro_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='tempo_processamento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
