# Generated by Django 5.1.5 on 2025-03-09 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0003_analise_n_basofilos_analise_n_eosinofilos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='analises/')),
                ('imagem_resultado', models.ImageField(blank=True, null=True, upload_to='resultados/')),
                ('n_plaquetas', models.IntegerField(blank=True, null=True)),
                ('n_celulas_brancas', models.IntegerField(blank=True, null=True)),
                ('n_celulas_vermelhas', models.IntegerField(blank=True, null=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_analise', to='Analises.analise')),
            ],
            options={
                'verbose_name': 'Imagem da Análise',
                'verbose_name_plural': 'Imagens das Análises',
            },
        ),
    ]
