# Generated by Django 5.1.5 on 2025-01-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0003_analise_tempo_processamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='n_celulas_brancas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='n_celulas_vermelhas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
