# Generated by Django 5.1.5 on 2025-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0004_analise_n_celulas_brancas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='historico_modificacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='ultima_modificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
