# Generated by Django 5.1.5 on 2025-03-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0004_imagemanalise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analise',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
