# Generated by Django 5.1.5 on 2025-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0005_analise_historico_modificacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='confianca_deteccao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='densidade_relativa',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='detalhes_processamento',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='metadados_modelo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
