# Generated by Django 5.1.5 on 2025-03-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0002_reset_analises'),
        ('Analises', '0005_alter_analise_id_alter_analise_titulo'),
    ]

    operations = [
    ]
