# Generated by Django 5.1.5 on 2025-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0006_merge_20250323_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
